on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: |
            r0123456_final.tex

      - name: Create or update latest release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: r0123456_final.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
