on:
  push:
    branches:
      - lowie
    paths:
      - "**/*.tex"
      - ".github/workflows/latex.yml"
  pull_request:
    branches:
      - lowie
    paths:
      - "**/*.tex"
      - ".github/workflows/latex.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: |
            r0123456_final.tex
            r0123456_intermediate.tex
            r0123456_peer_AI.tex
            r0123456_peer_human.tex

      - name: Create or update latest release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            r0123456_final.pdf
            r0123456_intermediate.pdf
            r0123456_peer_AI.pdf
            r0123456_peer_human.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
